version : "3"

services:

   springcloud:
      image: spring-cloud
      build: 
         context: ./spring-cloud-config-service
         dockerfile: Dockerfile
      ports:
         - "8888:8888"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888"]
        interval: 30s
        timeout: 10s
        retries: 5

   eureka:
      image: spring-eureka
      build:
         context: ./spring-cloud-eureka-service
         dockerfile: Dockerfile
      ports:
         - "8761:8761"      
      depends_on:
         - "springcloud"
      command:    
         []   
      